# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/anu/E P I C    S T U F F F/Academics/Fall sem 2018-2019/Network Security/Project/tor_file/DesignWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(772, 622)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.Tabs.setGeometry(QtCore.QRect(10, 0, 751, 581))
        self.Tabs.setObjectName("Tabs")
        self.encryptTab = QtWidgets.QWidget()
        self.encryptTab.setObjectName("encryptTab")
        self.browseBtn = QtWidgets.QPushButton(self.encryptTab)
        self.browseBtn.setGeometry(QtCore.QRect(660, 30, 75, 23))
        self.browseBtn.setObjectName("browseBtn")
        self.encryptBtn = QtWidgets.QPushButton(self.encryptTab)
        self.encryptBtn.setGeometry(QtCore.QRect(10, 300, 371, 23))
        self.encryptBtn.setObjectName("encryptBtn")
        self.lineEdit = QtWidgets.QLineEdit(self.encryptTab)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 641, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.serveBtn = QtWidgets.QPushButton(self.encryptTab)
        self.serveBtn.setGeometry(QtCore.QRect(394, 300, 351, 23))
        self.serveBtn.setObjectName("serveBtn")
        self.label = QtWidgets.QLabel(self.encryptTab)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.encryptTab)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.encryptTab)
        self.textBrowser.setGeometry(QtCore.QRect(10, 360, 721, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.label_3 = QtWidgets.QLabel(self.encryptTab)
        self.label_3.setGeometry(QtCore.QRect(10, 340, 47, 10))
        self.label_3.setObjectName("label_3")
        self.pub_key = QtWidgets.QPlainTextEdit(self.encryptTab)
        self.pub_key.setGeometry(QtCore.QRect(10, 80, 731, 211))
        self.pub_key.setObjectName("pub_key")
        self.Tabs.addTab(self.encryptTab, "")
        self.decryptTab = QtWidgets.QWidget()
        self.decryptTab.setObjectName("decryptTab")
        self.browseBtn_2 = QtWidgets.QPushButton(self.decryptTab)
        self.browseBtn_2.setGeometry(QtCore.QRect(660, 30, 75, 23))
        self.browseBtn_2.setObjectName("browseBtn_2")
        self.label_4 = QtWidgets.QLabel(self.decryptTab)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 111, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.decryptTab)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label_5.setObjectName("label_5")
        self.encryptBtn_2 = QtWidgets.QPushButton(self.decryptTab)
        self.encryptBtn_2.setGeometry(QtCore.QRect(10, 300, 731, 23))
        self.encryptBtn_2.setObjectName("encryptBtn_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.decryptTab)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 360, 721, 192))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_6 = QtWidgets.QLabel(self.decryptTab)
        self.label_6.setGeometry(QtCore.QRect(10, 340, 47, 10))
        self.label_6.setObjectName("label_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.decryptTab)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 30, 641, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pub_key_2 = QtWidgets.QPlainTextEdit(self.decryptTab)
        self.pub_key_2.setGeometry(QtCore.QRect(10, 80, 731, 211))
        self.pub_key_2.setObjectName("pub_key_2")
        self.Tabs.addTab(self.decryptTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 772, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.browseBtn.setText(_translate("MainWindow", "Browse"))
        self.encryptBtn.setText(_translate("MainWindow", "Encrypt the File"))
        self.serveBtn.setText(_translate("MainWindow", "Serve on Tor"))
        self.label.setText(_translate("MainWindow", "Browse File:"))
        self.label_2.setText(_translate("MainWindow", "Enter Public Key:"))
        self.label_3.setText(_translate("MainWindow", "Log:"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.encryptTab), _translate("MainWindow", "Encryption"))
        self.browseBtn_2.setText(_translate("MainWindow", "Browse"))
        self.label_4.setText(_translate("MainWindow", "Enter Private Key:"))
        self.label_5.setText(_translate("MainWindow", "Browse File:"))
        self.encryptBtn_2.setText(_translate("MainWindow", "Decrypt the File"))
        self.label_6.setText(_translate("MainWindow", "Log:"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.decryptTab), _translate("MainWindow", "Decrypt"))

